# Generated by Django 2.1.5 on 2019-12-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191222_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_time',
        ),
    ]
