# Generated by Django 2.1.5 on 2020-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_last_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('articleName', models.TextField()),
                ('content', models.TextField()),
                ('publishDate', models.TimeField(auto_now=True)),
            ],
        ),
    ]
