# Generated by Django 2.1.5 on 2020-01-15 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
