# Generated by Django 2.1.5 on 2020-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userNub',
            field=models.CharField(db_column='userNub', default=1552055936, max_length=20),
            preserve_default=False,
        ),
    ]
