# Generated by Django 3.0.2 on 2020-01-22 03:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_usernub'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('articleM', django.db.models.manager.Manager()),
            ],
        ),
    ]
