# Generated by Django 3.0.2 on 2020-01-22 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
