# Generated by Django 3.0.2 on 2020-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200122_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userNub',
            field=models.CharField(db_column='userNub', default=0, max_length=20),
        ),
    ]
