# Generated by Django 2.1.4 on 2020-06-14 14:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200123_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_column='用户', max_length=32, verbose_name='User')),
                ('token', models.CharField(db_column='token值', max_length=64)),
            ],
            managers=[
                ('tokenM', django.db.models.manager.Manager()),
            ],
        ),
    ]
