# Generated by Django 2.1.4 on 2020-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(db_column='token', max_length=64),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='uid',
            field=models.CharField(db_column='username', max_length=32),
        ),
    ]
